### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by arghadipmanna101** [Sayan67/Youtube-uploader#1]
- will add gif
- will stylize the readme
- will update how to contribute
- Will update contributors name in Readme file.

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by Sayan67** [comment]
Finish it by tomorrow. PR will be accepted only if the changes are valid and necessary. Unnecessary small changes will not be accepted.

**Comment by arghadipmanna101** [comment]
ok.

**Comment by arghadipmanna101** [comment]
how can i run the application?
I want to add some preview images

**Comment by Sayan67** [comment]
> how can i run the application? I want to add some preview images

As per the issue is suggesting you don't need to run the application though, still if you want to run the application there is a section in the Readme.md called "How to run locally". Follow that section.

You should have COMPLETE it by yesterday. I am extending the date to today, so hurry up🚀. Otherwise I have to close the issue.
